name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    env:
      PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
      PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set pub.dev credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${PUB_DEV_PUBLISH_ACCESS_TOKEN}",
            "refreshToken":"${PUB_DEV_PUBLISH_REFRESH_TOKEN}",
            "tokenEndpoint":"${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}",
            "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
            "expiration":${PUB_DEV_PUBLISH_EXPIRATION}
          }
          EOF

      - name: Check publish warnings
        run: |
          dart format lib
          dart format example
          pub publish --dry-run

      - name: Upload package to pub.dev
        run: pub publish -f
